### PR TITLE
feat: initial support for spraying in set commands

### PR DESCRIPTION
**Pull request by crankynetman**
I put in some really rudimentary support for spraying in set style JunOS commands. It's kinda hacky TBQH.

### CODE REVIEW

**Comment by hellt** [comment]
thanks a lot @crankynetman ! that looks good to me as a first approach. I have changed the config dir/file names, hope that is ok. Also black formatter did its black stuff on top.

I think we can also add in a separate PR an option to save the config to a file that will be located at the same `/config` directory and thus become available to the clab host

**Comment by hellt** [comment]
@crankynetman one little question for ya
since there is a new password prompt in vqfx 20.2 how do you go about it in your testing?

**Comment by chriscummings-esnet** [comment]
I haven't been able to get 20.2, when I download it from Juniper's site it still runs 19.something 🤦🏻‍♂️ . Agreed on the separate PR for the config save. Additionally, I'd like to add support for non-set format of commands (and there's probably a better ZTP method than `for each` on every line 😂  so this could totally be improved for larger configs.)

**Comment by crankynetman** [comment]
I haven't been able to get 20.2, when I download it from Juniper's site it still runs 19.something 🤦🏻‍♂️ . Agreed on the separate PR for the config save. Additionally, I'd like to add support for non-set format of commands (and there's probably a better ZTP method than for each on every line 😂  so this could totally be improved for larger configs.)

**Pull request merged**
