### PR TITLE
Dell OS10 improvements

### PR DESCRIPTION
**Pull request by jbemmel**
* Wait while system gives "loading" prompt
* Add note on qcow2 compression, reduced image to ~30% in my case for 10.5.6.6:
```-rw-r--r--  1 jvanbemmel jvanbemmel 2336227328 Oct 31 08:54 dellftos.10.5.6.6.qcow2```

More general changes:
* Refactor management IP network settings, make them configurable
* Change Dell OS10 management link to private 169.254.127.0/24 range, to minimize chance at overlap with other configs ( original 10.0.0.0/24 is way too common ... )
* Forward only the TCP ports used by the platform, not the full set of those used by all other platforms
* Address warnings caused by format strings to logger

### CODE REVIEW

**Comment by hellt** [comment]
Since #279 has been started, it would make sense to ensure that ftos works with the scrapli driver. The plan is to remove telnet scraping in a short while as it served its time

**Comment by jbemmel** [comment]
I’m fine with that, but can we accept this PR in the meantime until the ideal architecture is available?

FTOS is currently broken

**Comment by hellt** [comment]
@log1cb0mb, @ssasso, @nlgotz hi all, you have contributed to ftosv support in the past, since this PR is intrusive, would you care to try it out before it gets merged?

**Comment by jbemmel** [comment]
> @log1cb0mb, @ssasso, @nlgotz hi all, you have contributed to ftosv support in the past, since this PR is intrusive, would you care to try it out before it gets merged?

I didn't intend to submit those more radical refactorings as part of this PR, guess I forgot to switch branches - sorry

**Comment by ssasso** [comment]
It is working on my machine! :) tnx @jbemmel for solving the annoying "loading" stuff.

**Comment by hellt** [comment]
thnx @ssasso and @jbemmel

**Pull request merged**
