### PR TITLE
Add Ubuntu support

### PR DESCRIPTION
**Pull request by jmussmann**
This is a PR to add support for Ubuntu VMs. The code is based in the freebsd and openbsd code base of this repository.

For testing I used the below containerlab topology:

```yaml
name: vr-linux01

topology:
  nodes:
    ceos:
      kind: ceos
      image: ceos:4.31.2F
    ubuntu-01:
      kind: vr_linux
      image: vrnetlab/vr-ubuntu:jammy
    ubuntu-02:
      kind: vr_linux
      image: vrnetlab/vr-ubuntu:jammy
  links:
    - endpoints: ["ceos:eth1", "ubuntu-01:eth1"]
    - endpoints: ["ceos:eth2", "ubuntu-02:eth1"]
```

### CODE REVIEW

**Comment by jmussmann** [comment]
I have also added a PR to the containerlab repository:  ["Add Linux VM kind #1976"](https://github.com/srl-labs/containerlab/pull/1976)

**Comment by hellt** [comment]
Thanks @jmussmann 
Is there anything ubuntu-specific in this integration (besides the download) script that prevents us using it with, say, Rocky or Centos Stream or Fedora?

**Comment by jmussmann** [comment]
The kind should work with other distros, but I have not tested the cloud init configuration. At container lab I created a more general name (vr_linux).

**Comment by hellt** [comment]
done in #198

**Pull request closed without merging**
