### PR TITLE
Fix to support the Juniper vQFX

### PR DESCRIPTION
**Pull request by rokernel**
Currently the vQFX support is broken. This PR will allow the Juniper vQFX to properly start.

Tested with version: 15.1X53-D60

### CODE REVIEW

**Comment by hellt** [comment]
thanks @rokernel 
do you also want to add a piece in containerlab for that? or do you only need this for docker native networking?

**Comment by rokernel** [comment]
> thanks @rokernel
> do you also want to add a piece in containerlab for that? or do you only need this for docker native networking?

My target is to support both, so please go ahead and update containerlab too.

Thank you

**Comment by hellt** [comment]
do you gents have an image of vqfx for me to test?

**Comment by chriscummings-esnet** [comment]
I figured out a better regex for sed that should work better with newer images. This got an image based off of 18.4R1.8 working with vrnetlab. 

I'd add a commit to this pr, but I'm not sure how to do that without having push access to either repo, so here's the line:

`VERSION=$(shell echo $(IMAGE) | sed -re 's/vqfx10k-re-([^;]*).vmdk.*$$/\1/')`

**Comment by chriscummings-esnet** [comment]
@rokernel I think if you add this patch it will do everything that is needed for containerlab to work with various versions of vQFX and I'm adding a PR to containerlab to setup all of the clab side of things (already tested and working).

```
diff --git a/vqfx/Makefile b/vqfx/Makefile
index eb99cb3..8550cdb 100644
--- a/vqfx/Makefile
+++ b/vqfx/Makefile
@@ -5,7 +5,7 @@ IMAGE_GLOB=*.vmdk
 
 # match versions like:
 # vqfx10k-re-15.1X53-D60.vmdk
-VERSION=$(shell echo $(IMAGE) | sed -e 's/^vqfx10k-re-\([0-9][0-9]\.[0-9][A-Z][0-9]\+\(\.[0-9]\+\)\?\(-D[0-9]\+\)\)[^0-9].*$$/\1/')
+VERSION=$(shell echo $(IMAGE) | sed -re 's/vqfx10k-re-([^;]*)\.vmdk.*$$/\1/')
 
 -include ../makefile-sanity.include
 -include ../makefile.include
diff --git a/vqfx/docker/launch_vqfx.py b/vqfx/docker/launch_vqfx.py
index 62b86b5..c6903ea 100755
--- a/vqfx/docker/launch_vqfx.py
+++ b/vqfx/docker/launch_vqfx.py
@@ -30,13 +30,14 @@ logging.Logger.trace = trace
 
 
 class VQFX_vcp(vrnetlab.VM):
-    def __init__(self, username, password, conn_mode):
+    def __init__(self, hostname, username, password, conn_mode):
         for e in os.listdir("/"):
             if re.search("-re-.*.vmdk", e):
                 vrnetlab.run_command(["qemu-img", "create", "-b", "/" + e, "-f", "qcow", "/vcp.qcow2"])
         super(VQFX_vcp, self).__init__(username, password, disk_image="/vcp.qcow2", ram=2048)
         self.num_nics = 12
         self.conn_mode = conn_mode
+        self.hostname = hostname
 
 
     def start(self):
@@ -131,6 +132,7 @@ class VQFX_vcp(vrnetlab.VM):
         self.wait_write("delete interfaces")
         self.wait_write("set interfaces em0 unit 0 family inet address 10.0.0.15/24")
         self.wait_write("set interfaces em1 unit 0 family inet address 169.254.0.2/24")
+        self.wait_write(f"set system host-name {self.hostname}")
         self.wait_write("commit")
         self.wait_write("exit")
 
@@ -205,10 +207,10 @@ class VQFX(vrnetlab.VR):
     """ Juniper vQFX router
     """
 
-    def __init__(self, username, password, conn_mode):
+    def __init__(self, hostname, username, password, conn_mode):
         super(VQFX, self).__init__(username, password)
 
-        self.vms = [ VQFX_vcp(username, password, conn_mode), VQFX_vpfe() ]
+        self.vms = [ VQFX_vcp(hostname, username, password, conn_mode), VQFX_vpfe() ]
 
         # set up bridge for connecting VCP with vFPC
         vrnetlab.run_command(["brctl", "addbr", "int_cp"])
@@ -220,6 +222,7 @@ if __name__ == '__main__':
     import argparse
     parser = argparse.ArgumentParser(description='')
     parser.add_argument('--trace', action='store_true', help='enable trace level logging')
+    parser.add_argument("--hostname", default="vr-vqfx", help="QFX hostname")
     parser.add_argument('--username', default='vrnetlab', help='Username')
     parser.add_argument('--password', default='VR-netlab9', help='Password')
     parser.add_argument('--install', action='store_true', help='Install vQFX')
@@ -238,5 +241,5 @@ if __name__ == '__main__':
     if args.trace:
         logger.setLevel(1)
     vrnetlab.boot_delay()
-    vr = VQFX(args.username, args.password, conn_mode=args.connection_mode)
+    vr = VQFX(args.hostname, args.username, args.password, conn_mode=args.connection_mode)
     vr.start()
```
[Here](https://github.com/hellt/vrnetlab/files/7197693/vrnetlab_vqfx_patch.txt) is the patch file if you want to test it yourself.

**Comment by hellt** [comment]
@chriscummings-esnet nice! is this supposed to work with both vmx17 and fresh vmx19+?

**Comment by chriscummings-esnet** [comment]
So far I have only tested with vQFX 18.4R1.8, but I _think_ it should work with any version that uses the pfe and re dual-VM model. Let me see if I can find some old images and test!

**Comment by hellt** [comment]
@oh, sorry, I think 18+ is good, confused the versions
this work has the stuff that is referenced here? https://github.com/plajjan/vrnetlab/pull/234

**Comment by chriscummings-esnet** [comment]
Hrmmm, no it doesn't add that stuff, I just worked out of this branch/pr and hadn't seen this yet. My images are .vmdk and must predate this change by Juniper. 🤦🏻‍♂️

**Comment by hellt** [comment]
superseded by #64 
lets work on the merged #64 to make this support better

**Pull request closed without merging**
