### PR TITLE
Replace GNS3 PPA with netdevops gemfury repo (for IOUYAP) in IOL Dockerfile

### PR DESCRIPTION
**Pull request by kaelemc**
As the title says. Replace the GNS3 PPA with the netdevops.fury gemfury repo which hosts the custom build of IOUYAP that @DanPartelly has made.

Will take it out of draft status once testing is complete.

### CODE REVIEW

**Review by hellt — APPROVED** [review]

**Comment by DanPartelly** [comment]
Ive tested the PR branch. The images are built OK.  Ive also rerun the test suite. It passes.

Just please add the reason the change was made in the final commit. i.e "The change was necessary because iouyap did not account was Linux kernel stripping dot 1q headers from packets captured with a raw socket. The result was VLANs where broken on both iol devices. The new version reconstructs the headers correctly."

**Comment by silverwind** [comment]
The apt source https://netdevops.fury.site/apt is 404, any alternatives?

**Comment by kaelemc** [comment]
@silverwind It's 404 for me but I can still get the package lists just fine + the build still works (even w/ clean build via `docker builder prune --all`). 

I get '404 Not Found' on `/apt`, but I get 'Not Found' on `/apt/`

Regardless you can also get the pkg from here:
https://download.opensuse.org/repositories/home:/danp/Debian_12/amd64/

**Comment by silverwind** [comment]
Ah, I think what might have been the problem is that I'm building on `arm64` architecture and there are no packages for that on that apt repo. Instead managed to build https://github.com/GNS3/iouyap from source, hope that's the right repo.

**Comment by kaelemc** [comment]
Understood. That repo will work, but it won't handle VLANs correctly. 

We are using a patched version at: https://github.com/danpartelly/iouyap.

I'm intrigued to hear about IOL on arm. If you can please let me know if it works well (if at all) 😃

**Comment by silverwind** [comment]
Thanks, I will try with that fork. I wonder too if it can work. I'll attempt to build a multi-arch image with arm64+amd64.

**Comment by hellt** [comment]
This will be great, @silverwind 
Though IOL works on macos/arm64 under Rosetta, it has perf issues sometimes, so having a native arm version would be amazing.

**Comment by kaelemc** [comment]
Unless I'm missing something here, you'll always have to emulate since IOL is a prebuilt binary, unless you have the source 😉.

**Comment by hellt** [comment]
yup, if IOL for arm64 is not available in the refplat, then iouyap alone will not gain much performance, but still a little bit better

**Pull request merged**
