### PR TITLE
vSRX - adding code to launch.py to load startup config

### PR DESCRIPTION
**Pull request by sonicepk**
vSRX - adding code to launch.py to load startup config. 

topology:
  nodes:
    node:
      kind: vr-vsrx
      startup-config: myconfig.txt

### CODE REVIEW

**Comment by hellt** [comment]
@rfc2516 @ssasso Hi there, do you mind sharing your review comments if any?

**Comment by ssasso** [comment]
The code looks good to me.

However, better to write somewhere (in the documentation?) that the "startup file" must be a list of set commands, and not a "real" junos startup file.

Potentially, if @sonicepk would like to improve this, it could check the file for the "set" directives, and
* print the set commands to the console, if the file is a list of set
* use `load merge terminal` in case it is a junos startup file

**Comment by ssasso** [comment]
(side note:

https://github.com/hellt/vrnetlab/blob/master/vjunosswitch/

uses a different approach, having both the default config + custom user config file in "junos format" - see https://github.com/hellt/vrnetlab/blob/ca3131c081ee352f275c9610af9330a49e461bbd/vjunosswitch/docker/launch.py#L100

)

**Comment by sonicepk** [comment]
@ssasso Good idea about providing support for both formats. I tested this code with Juniper set and Junos formatted startup config files and it worked. On a couple of occasions the CTL-D didn't work. Hence the two CTL-D and CTL-Rs. Just to be sure...

**Comment by hellt** [comment]
@sonicepk so is it now supporting two config flavors? Ready to merge?

**Comment by johncrack** [comment]
I tried it and it is working partially.

With the following file, the "p1" hostname isn't applied. The rest is okay. However if I move "set system host-name p1" at the end of the file, it works.

```
[root@containerlab pod1]# cat p1.txt 
set system host-name p1
set system root-authentication encrypted-password "$6$XmlrjA7A$uU.JdzznaN1Cg37ZJMd9QFFyuYyAyVDQYSSzPfCp0pzz0wgI9wHP.gwQLGPGROKqISKlIP.pJDTILZSvZDit20"
set system login user admin uid 2000
set system login user admin class super-user
set system login user admin authentication encrypted-password "$6$9WDPuV.L$ZakdL8aVNU6r6ykvT2rbyhETgYb6IHw5FRuq6yd22MD8mHrQmuqYQ37M3bZsfHYoEawz9CF2a3lA3FQRUD2Lq/"
set system services ssh
set system services netconf ssh
set system management-instance
set security forwarding-options family mpls mode packet-based
set interfaces ge-0/0/0 unit 0 family inet address 169.254.0.6/30
set interfaces ge-0/0/1 unit 0 family inet address 169.254.0.18/30
set interfaces ge-0/0/2 unit 0 family inet address 169.254.0.21/30
set interfaces ge-0/0/3 unit 0 family inet address 169.254.0.25/30
set interfaces ge-0/0/4 unit 0 family inet address 169.254.0.37/30
set interfaces ge-0/0/5 unit 0 family inet address 169.254.0.41/30
set interfaces fxp0 unit 0 family inet address 10.0.0.15/24
set interfaces lo0 unit 0 family inet address 10.1.1.3/32
set interfaces fxp0 unit 0 family inet address 10.0.0.15/24
set routing-instances mgmt_junos routing-options static route 0.0.0.0/0 next-hop 10.0.0.2
set routing-instances mgmt_junos description management-instance
set protocols ospf area 0.0.0.0 interface ge-0/0/0.0
set protocols ospf area 0.0.0.0 interface ge-0/0/1.0
set protocols ospf area 0.0.0.0 interface ge-0/0/2.0
set protocols ospf area 0.0.0.0 interface ge-0/0/3.0
set protocols ospf area 0.0.0.0 interface ge-0/0/4.0
set protocols ospf area 0.0.0.0 interface ge-0/0/5.0
set protocols ospf traceoptions file ospf.log
set routing-options router-id 10.1.1.3
```

**Comment by sonicepk** [comment]
> @sonicepk so is it now supporting two config flavors? Ready to merge?

Yes, it does support both formats.

**Comment by sonicepk** [comment]
> I tried it and it is working partially.
> 
> With the following file, the "p1" hostname isn't applied. The rest is okay. However if I move "set system host-name p1" at the end of the file, it works.
> 
> ```
> [root@containerlab pod1]# cat p1.txt 
> set system host-name p1
> set system root-authentication encrypted-password "$6$XmlrjA7A$uU.JdzznaN1Cg37ZJMd9QFFyuYyAyVDQYSSzPfCp0pzz0wgI9wHP.gwQLGPGROKqISKlIP.pJDTILZSvZDit20"
> set system login user admin uid 2000
> set system login user admin class super-user
> set system login user admin authentication encrypted-password "$6$9WDPuV.L$ZakdL8aVNU6r6ykvT2rbyhETgYb6IHw5FRuq6yd22MD8mHrQmuqYQ37M3bZsfHYoEawz9CF2a3lA3FQRUD2Lq/"
> set system services ssh
> set system services netconf ssh
> set system management-instance
> set security forwarding-options family mpls mode packet-based
> set interfaces ge-0/0/0 unit 0 family inet address 169.254.0.6/30
> set interfaces ge-0/0/1 unit 0 family inet address 169.254.0.18/30
> set interfaces ge-0/0/2 unit 0 family inet address 169.254.0.21/30
> set interfaces ge-0/0/3 unit 0 family inet address 169.254.0.25/30
> set interfaces ge-0/0/4 unit 0 family inet address 169.254.0.37/30
> set interfaces ge-0/0/5 unit 0 family inet address 169.254.0.41/30
> set interfaces fxp0 unit 0 family inet address 10.0.0.15/24
> set interfaces lo0 unit 0 family inet address 10.1.1.3/32
> set interfaces fxp0 unit 0 family inet address 10.0.0.15/24
> set routing-instances mgmt_junos routing-options static route 0.0.0.0/0 next-hop 10.0.0.2
> set routing-instances mgmt_junos description management-instance
> set protocols ospf area 0.0.0.0 interface ge-0/0/0.0
> set protocols ospf area 0.0.0.0 interface ge-0/0/1.0
> set protocols ospf area 0.0.0.0 interface ge-0/0/2.0
> set protocols ospf area 0.0.0.0 interface ge-0/0/3.0
> set protocols ospf area 0.0.0.0 interface ge-0/0/4.0
> set protocols ospf area 0.0.0.0 interface ge-0/0/5.0
> set protocols ospf traceoptions file ospf.log
> set routing-options router-id 10.1.1.3
> ```

Thanks for testing, and yes that was a bug. Basically I was checking if the the files starts with a set command and if if did I read the remainder of the file. Fixed it by writing the first line now and then the remainder of the file.

**Pull request merged**
