### PR TITLE
update Cisco CSR 1000v for support with containerlab

### LINKED ISSUE #43: CSR1000v make fails due to f-string in vrnetlab.py
CSR1000v docker file is set to use Debian:stretch which installs python 3.5.3 which does not support f-strings. (fstring support was added in python 3.6 I beleive). As f-strings are used in vrnetlab.py this causes the build to fail with a syntax error:

```
Step 10/10 : ENTRYPOINT ["/launch.py"]
 ---> Using cache
 ---> 6388d8f13b7b
Successfully built 6388d8f13b7b
Successfully tagged vrnetlab/vr-csr:16.11.01b
docker run --cidfile cidfile --privileged vrnetlab/vr-csr:16.11.01b --trace --install
Traceback (most recent call last):
  File "/launch.py", line 13, in <module>
    import vrnetlab
  File "/vrnetlab.py", line 51
    logging.getLogger().info(f"Delaying VM boot of by {delay} seconds")
                                                                     ^
SyntaxError: invalid syntax
make[1]: *** [Makefile:19: docker-build] Error 1
make[1]: Leaving directory '/home/denis/vrnetlab/csr'
```

Changing docker to use to debian:buster resolves that issue, but then get errors on conn_mode not existing on the CSR class...

### PR DESCRIPTION
**Pull request by dpnetca**
Fixes #43 

Update to CSR 1000v files for support with containerlab

- Updated Dockerfile from debian Stretch to Ubuntu 20.04, added additional packages similar to done with other updated components
- added hostname, nics, and conn_mode flags to launch.py
- added delay to gen_nics, without it, interfaces would not reliably appear on images
- added nic_type to CSR class specifying virtio, default of e1000 not supported with current  CSR ios.
- updated README to indicate tested version 17.03.02

tests with versions 16.12 and 16.11 both failed as gig1 was not created

### CODE REVIEW

**Comment by hellt** [comment]
on my 17.03.03 I noticed that command `ip domain-name $name` doesn't work
I changed it to `ip domain name $name`.

Didn't you see the errors like this in your log?

```
2021-04-07 07:02:42,563: vrnetlab   DEBUG    writing to serial console: username admin privilege 15 password admin
2021-04-07 07:02:42,563: vrnetlab   TRACE    waiting for '#' on serial console
2021-04-07 07:02:42,614: vrnetlab   TRACE    read from serial console: hostname csr
csr(config)#
2021-04-07 07:02:42,614: vrnetlab   DEBUG    writing to serial console: ip domain-name example.com
2021-04-07 07:02:42,614: vrnetlab   TRACE    waiting for '#' on serial console
2021-04-07 07:02:42,684: vrnetlab   TRACE    read from serial console: username admin privilege 15 password admin
 WARNING: Command has been added to the configuration using a type 0 password. However, type 0 passwords will soon be deprecated. Migrate to a supported password type
csr(config)#
2021-04-07 07:02:42,684: vrnetlab   DEBUG    writing to serial console: crypto key generate rsa modulus 2048
2021-04-07 07:02:42,684: vrnetlab   TRACE    waiting for '#' on serial console
2021-04-07 07:02:42,728: vrnetlab   TRACE    read from serial console: ip domain-name example.com
                     ^
% Invalid input detected at '^' marker.
```

**Comment by hellt** [comment]
What I am trying to find out as well is if csr1000v can have gNMI protocol enabled
for whatever reason, the `gnmi-yang` command is not found on my 17.03 system...

**Comment by hellt** [comment]
unfortunately with the `csr1000v-universalk9.17.03.03-serial.qcow2` that I have, I still experience Gi1 not showing up...

**Comment by dpnetca** [comment]
corrected the domain name issue command should of been `ip domain name ...` not domain-name.  

I've been testing with 17.03.02  will download 17.03.03 and see if I see the same issues with G1...perhaps it working with 17.3.2 is just an anomaly. I'll take a look again today, if I can get it working in 17.3.3 perhaps that will get it working in older versions as welll.

**Comment by hellt** [comment]
I think something is with the `install` step that might interfere here. What I'd try is to manually launch the setup phase as explained [here](https://www.eve-ng.net/index.php/documentation/howtos/howto-add-cisco-csrv1000-16-x-denali-everest-fuji/) and use the produced image without the install step with vrnetlab.

Another option would be to check with the vrnetlab community and see if anyone saw similar issues.

**Comment by dpnetca** [comment]
ok, so the install flag is booting up the router, installing the license file if you have one, and setting platform console serial.   The steps in the doc you listed is setting the platform console serial.  if you use the serial image, then this step isn't really required.  

If I comment out the lines below in the CSR Makefile then it doesn't run the install when building the docker.  this doesn't solve anything though (although it makes building the image way quicker....).  the only thing that is missing then is the license install, but that can probably be handled differently.

```
#docker-pre-build:
       -cat cidfile | xargs --no-run-if-empty docker rm -f
       -rm cidfile

#docker-build: docker-build-common
       docker run --cidfile cidfile --privileged $(REGISTRY)vr-$(VR_NAME):$(VERSION) --trace --install
       docker commit --change='ENTRYPOINT ["/launch.py"]' $$(cat cidfile) $(REGISTRY)vr-$(VR_NAME):$(VERSION)
       docker rm -f $$(cat cidfile)
```

Looks like what is causing the issues is this statement in the /common/vrnet.py script in the gen_nics() function

```
for i in range(1, self.num_nics + 1):
    # if the matching container interface ethX doesn't exist, we don't create a nic
    if not os.path.exists(f"/sys/class/net/eth{i}"):
           continue           
```
`/sys/class/net/eth1` or higher doesn't exist so it skips the rest of the loop, never builds the device to add to the qemu launch statement


gen_nics() is one of the functions the was changed fairly significantly from  from what was in plajjan/vrnetlab version.  I coped the gen_nics() function from plajjan/vrnetlab into my launch.py to override the custom one and that works, my CSR's launch with interfaces showing up as expected, however, missing the customization here I assume it's not going to work properly in contaienrlab.  I'm not really sure how to solve this yet though, need to spend some mroe tim understanding what all is happening in this function.

**Comment by hellt** [comment]
> Looks like what is causing the issues is this statement in the /common/vrnet.py script in the gen_nics() function

```
for i in range(1, self.num_nics + 1):
    # if the matching container interface ethX doesn't exist, we don't create a nic
    if not os.path.exists(f"/sys/class/net/eth{i}"):
           continue     
```

So what this loop does is that it checks if any `ethX` interfaces were created inside the docker container. When we launch the container with qemu vm inside, we also add interfaces to it, these are the data interfaces and they have names `eth1, eth2, eth3, etc`.

Depending on how many interfaces you attached to a node defined in container lab you will get a number of `eth1+` interfaces inside of a container.

As you rightly pointed out, it is best to introduce a timer like `time.sleep(5)` before calling `gen_nics()` to let those `eth1+` interfaces to appear inside the container. This doesn't seem to cause the issue though...

When the gen_nics function works as expected, you should see in the logs of the container that we added interfaces to qemu process, one interface per one data port added.

When the install() function works, we do not attach any data interfaces, but that seems to be ok?

**Comment by hellt** [comment]
I have received a comment on ntc slack, that 17.03 was failing to boot for someone else as well, and 17.01 was the last image they managed to get started

image

**Comment by hellt** [comment]
One other comment from good ntc folks which might help in trying things

```
cfg_file.write("do clear platform software vnic-if nvtable\r\n\r\n")
```

this is expanded here and by quickly glancing over it https://www.cisco.com/c/en/us/td/docs/routers/csr1000/software/configuration/b_CSR1000v_Configuration_Guide/b_CSR1000v_Configuration_Guide_chapter_01010.html it might help.
The assumption is that during the install there is this mythical nic<->mac table gets populated, which needs to be cleared before commiting the image.

Worth trying imo

**Comment by dpnetca** [comment]
> So what this loop does is that it checks if any ethX interfaces were created inside the docker container. When we launch the container with qemu vm inside, we also add interfaces to it, these are the data interfaces and they have names eth1, eth2, eth3, etc.

When / where are those interfaces being added?, or rather supposed to be added?  I'm walking through the scrips and I don't see where that is happening?  or is this something being done by the containerlab scripts?

following through the launch.py flow I at the time this for loop is run we've 

- instantiated the CSR class
   - run the init for vrnetlab.VR which creates a tftpboot folder
- Instantiated the CSR_VM class
   -  run the init for vrnetlab.VM, at this point we've set some variable values only
- here we run a couple socat commands to listen to SSH, syslog, etc.
- then we start digging into the vm's we call the vm.work function which calls the check_qemu function which calls the start function under the vrnetlab.VR class
  -  this function starts building the qemu command, including calling the gen_nics function.  which is checkling if the interface is created


So, either we are missing a step in there to create the nics am missing where they are supposed to be created or I'm looking in the wrong spot (I am assuming I am looking in the wrong spot or just overlooking it, as the the XRV9K has the same flow).

**Comment by hellt** [comment]
> When / where are those interfaces being added?, or rather supposed to be added? I'm walking through the scrips and I don't see where that is happening? or is this something being done by the containerlab scripts?

yes, when you define a node in containerlab you also define links that this node will have
by default `eth0` interface will always appear in the container, that is managed by docker

but when a user specifies links section in the topology definition file, i.e. like this:

```yaml
# this lab is meant to serve a testing purpose to validate that various sros images at least boot
name: sros-test

topology:
  nodes:
    sr1:
      kind: vr-sros
      image: vrnetlab/vr-sros:21.2.R1
    sr2:
      kind: vr-sros
      image: vrnetlab/vr-sros:21.2.R1
  links:
  - endpoints: ["sr1:eth1", "sr2:eth1"]
```

then both containers will have another interface added by containerlab named `eth1`.

In `launch.py` we check how many those `eth1+` interfaces get added to container (by containerlab) and will act accordingly in `gen_nics()` method

**Comment by dpnetca** [comment]
I should also note if I make the docker images using the current checked in scripts, and run then run container lab using my partially modified container lab (forked to: https://github.com/dpnetca/containerlab/tree/csr1000v) CSR 17.03.02 and 17.03.03 seem to work  (16.12.05B doesn't create gig 1, it created gig 2,3,4 instead).

using the topo setup below I get all 3 CSR's created, CSR1 and CSR2 have gig1 , gig2 and gig3 created and working as expected.  CSR3, does not create gig 1 (creates gig2,3,4 instead) 

```
$ cat csrlab.yaml 
name: csrlab

topology:
  nodes:
    csr1:
      kind: vr-csr
      image: vrnetlab/vr-csr:17.03.02
    csr2:
      kind: vr-csr
      image: vrnetlab/vr-csr:17.03.03
    csr3:
      kind: vr-csr
      image: vrnetlab/vr-csr:16.12.05

  links:
    - endpoints: ["csr1:eth1", "csr2:eth1"]
    - endpoints: ["csr1:eth2", "csr3:eth1"]
    - endpoints: ["csr2:eth3", "csr3:eth2"]
```

if I comment out the install steps from the Makefile then all three CSR's all versions load as expected.
If I add `cfg_file.write("do clear platform software vnic-if nvtable\r\n\r\n")` to the create_boot_image right before the wr and reload ....

note if you run the images with `docker run -d --privileged ...`  the gig1 interfaces are created from the gen_mgmt function, but the gen_nic funtion won't create the other interfaces.  but like i said it does work fine when launched using containerlab

**Comment by hellt** [comment]
let me try it out once again
what I see that you did differently in your containerlab for is that you used clab:clab@123 credentials, whereas I left them admin:admin

I will first try with admin:admin and your current checked in code in this PR on the 17.03 image that I have.
btw, lets compare the images that we have?

```
❯ md5sum csr1000v-universalk9.17.03.03-serial.qcow2 
69a74084e2625420d5d45ed126259f02  csr1000v-universalk9.17.03.03-serial.qcow2
```

**Comment by hellt** [comment]
@dpnetca I just rebuilt 17.03.03 and used the same code that I have in here https://github.com/srl-labs/containerlab/pull/369 and it worked
Gi1 is there

```
csr(config)#do show ip int br
Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet1       10.0.0.15       YES manual up                    up
GigabitEthernet2       unassigned      YES unset  administratively down down
```

I need to test if datapath is working

**Comment by hellt** [comment]
@dpnetca to mee it looks good, it works on my bench and on yours, so I am willing to merge it
if you do not have any other comments/additions, I will merge it

**Comment by dpnetca** [comment]
excellent  looks good to me :)

**Pull request merged**
